[Feature] login view
YuHangHuPXL/onBoarding pull request #4
Opened 2024-02-28 21:29 UTC by YuHangHuPXL

This pull request is for the login view. 

# Standard layout 
![image](https://github.com/YuHangHuPXL/onBoarding/assets/92795003/a6e502a3-bf29-4408-b331-ff5b8940a126)

- Button is disabled as long as either input fields are empty
- Clicking and holding the eye button shows password in plain text

# Validation

![image](https://github.com/YuHangHuPXL/onBoarding/assets/92795003/7eb1b044-1ad8-414b-bc69-9f5fc5fe10d9)

- Input fields are validated using regex. Red text will appear with a red border if the inputted value doesn't meet the requirements.
- A red textbox will appear if the user tries to log in with the wrong credentials

2024-02-28 21:40 UTC, maltsavkiryl requested changes
Looking very good 💯 Heb wat remarks achtergelaten om te laten zien hoe wij het zouden aanpakken

2024-02-28 21:40 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +						<svg
die SVG's kan je extracten naar een component

2024-02-28 21:40 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +	return username.value === '' || password.value === ''
Probeer hier eens onze "formango" package te gebruiken. Dan kan je een zod schema gebruiken om uw validation af te handelen. Zie onboarding en frontendbible voor meer info 😎

2024-02-28 21:40 UTC, maltsavkiryl commented on src/modules/auth/views/AuthLoginView.vue
> +async function handleLogin(data: { username: string; password: string }): Promise<void> {
beter om een type te gebruiken ipv `{ username: string; password: string }`

2024-02-28 21:40 UTC, maltsavkiryl commented on src/plugins/i18n/locales/jap.json
> +    "no_account_question": "なぜまだアカウントを作成していないのですか?",
Hahaha sick dit 🥇

2024-02-28 21:40 UTC, maltsavkiryl commented on src/modules/auth/views/AuthLoginView.vue
> +			<h2 class="text-3xl font-bold">{{ t('login.welcome_title') }}</h2>
Het is een kleine applicatie, maar je kan bijna voor alles components maken. Bijvoorbeeld een "AppText" of "AppTitle" component waar je text aan kan meegeven

2024-02-28 21:40 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +			<button
Hier zou het ook heel interessant zijn om een `AppButton` component te maken waar je verschillende props aan kunt meegeven en de styling kunt wegsteken

2024-02-28 21:40 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +				<input
Voor uw input components kan je ook een `AppInput` component maken om alle styling in weg te steken. Dan heb je minder duplicate code ;)

2024-02-29 08:44 UTC, maltsavkiryl requested changes
nog 1 kleine remark, looking very good mate 💯

2024-02-29 08:44 UTC, maltsavkiryl commented on src/components/button/AppButton.vue
> +withDefaults(
wij verplichten om altijd de `props` prefix te definen en te gebruiken in uw template. Voor Vue moet dat niet, maar als je een grote applicatie aan het bouwen zijt, dan is het gemakkelijk om te vergeten waar bepaalde variabelen vandaan komen

2024-02-29 08:44 UTC, maltsavkiryl commented on src/components/button/AppButton.vue
> +		<span>{{ buttonText }}</span>
in dit geval `{{ props.buttonText }}`

2024-02-29 08:44 UTC, maltsavkiryl commented on src/modules/auth/components/AuthLoginForm.vue
> +	<div class="container">
deze file ziet er al veeeeeeel beter en cleaner uit 👌 👌

2024-03-04 09:44 UTC, JeroenVanC requested changes

2024-03-04 09:44 UTC, JeroenVanC commented on src/components/text/AppText.vue
> +		text: 'test',
default is hier niet nodig, test mag weg

2024-03-04 09:44 UTC, JeroenVanC commented on src/components/input/AppInput.vue
> +		placeholder: 'shared.app_text_placeholder',
placeholder moet ook geen placeholder hebben

2024-03-04 09:44 UTC, JeroenVanC commented on src/components/input/AppInput.vue
> +watch(input, (newValue) => {
De v-model manier is veel gemakkelijker dan dit. of defineModel gebruiken

2024-03-04 09:44 UTC, JeroenVanC commented on src/components/text/AppText.vue
> +		text: 'test',
niet nodig

2024-03-04 09:44 UTC, JeroenVanC commented on src/components/title/AppTitle.vue
> +		titleText: 'Welcome!',
niet nodig

2024-03-04 09:44 UTC, JeroenVanC commented on src/icons/EyeIcon.vue
> +<script setup lang="ts"></script>
script niet nodig

2024-03-04 09:44 UTC, JeroenVanC commented on src/models/auth/authLoginForm.model.ts
> +export type AuthLoginInput = z.infer<typeof authLoginSchema>
AuthLoginForm is beter

2024-03-04 09:44 UTC, JeroenVanC commented on src/modules/auth/components/AuthLoginForm.vue
> +	emit('submit', values)
zelfde opmerking als ik tegen thomas had gzeged, zou dit in uw parent doen zonder emit

2024-10-22 11:45 UTC, closed without merging